### ISSUE TITLE
No agregar selectores en los fixture

### ISSUE THREAD

**Issue by FabrizioOtranto** [mhooes/pushingit-preentrega#2]
L:os fixtures se utilizan para pasar  data(informacion) al test no para inicializar selectores

https://github.com/mhooes/pushingit-preentrega/blob/472df5ad4d69fb2ea242072bae0c9eb7fea26b04/cypress/fixtures/products.json#L11

**Comment by mhooes** [comment]
Corregido, https://github.com/mhooes/pushingit-preentrega/blob/5b1491bf45713e8680c2fe0c34de220e23416088/cypress/fixtures/products.json#L1-L10
