### ISSUE TITLE
Metodo unico

### ISSUE THREAD

**Issue by FabrizioOtranto** [mhooes/pushingit-preentrega#3]
Debe ser un metodo unico que toma como parametro el producto a agregar!

https://github.com/mhooes/pushingit-preentrega/blob/5b1491bf45713e8680c2fe0c34de220e23416088/cypress/support/pages/onlineShop.js#L10

**Comment by mhooes** [comment]
Buen dia Fabri, te paso para ver si esto esta bien.
https://github.com/mhooes/pushingit-preentrega/blob/76ddb7f3e8be88b8449f0af53219d675d91097f5/cypress/support/pages/onlineShop.js#L9-L12
