### ISSUE TITLE
Debe ser un unico metodo

### ISSUE THREAD

**Issue by FabrizioOtranto** [mhooes/pushingit-preentrega#4]
Unico metodo que toma como parametro el producto para verificar el nombre!

https://github.com/mhooes/pushingit-preentrega/blob/5b1491bf45713e8680c2fe0c34de220e23416088/cypress/support/pages/shoppingCart.js#L3

**Comment by mhooes** [comment]
Corregido.
https://github.com/mhooes/pushingit-preentrega/blob/76ddb7f3e8be88b8449f0af53219d675d91097f5/cypress/support/pages/shoppingCart.js#L3-L6
