### ISSUE TITLE
Falta un metodo para verificar el precio

### ISSUE THREAD

**Issue by FabrizioOtranto** [mhooes/pushingit-preentrega#5]
Agrega un metodo que tome como parametro el producto y devolver el precio del producto (utilizando sibblings) y verificar el precio en el test!

https://github.com/mhooes/pushingit-preentrega/blob/5b1491bf45713e8680c2fe0c34de220e23416088/cypress/support/pages/shoppingCart.js#L14

**Comment by mhooes** [comment]
Corregido.
https://github.com/mhooes/pushingit-preentrega/blob/76ddb7f3e8be88b8449f0af53219d675d91097f5/cypress/support/pages/shoppingCart.js#L8-L11
